import wselect


"""
Simple stochastic L-system:
    input: axioms, rules, and iterations of the L-system
    output: string generated by applying rules to axioms after several iterations
"""
def stocLSystem(axioms, rules, iterations):
    for i in range(iterations):
        newAxioms = ''
        for symbol in axioms:
            if symbol in rules:
                newAxioms = ''.join([newAxioms, wselect.select(rules[symbol][0], rules[symbol][1])])
            else:
                newAxioms = ''.join([newAxioms, symbol])
        axioms = newAxioms
    
    return axioms


#Simple example
axioms = ['A']
rules = {'A': [['B', 'AB'], [.80, .20]], 'B': [['ACA', 'C'], [.80, .20]]}
iterations = 5

print(stocLSystem(axioms, rules, iterations))
    
            


